format_version: 10
pipelines:
  PP-Acme:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-35c20ad:
        git: https://github.com/AppFactorIo/acme.git
        username: ''
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - BuildNTest:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          buildNtest:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
